### ISSUE TITLE
Thank you!! Great demo, saved my a**, one question

### ISSUE THREAD

**Issue by lessenmytaxes** [pi0/nuxt-plesk-demo#4]
For the sake of good housekeeping, I want to put the server.js file in a server folder, because of routes, apis, controls, db, etc ....

Just too muddied to put all in root.

I edited web config to this:
```
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="server">
          <match url="/*" />
          <action type="Rewrite" url="server/server.js" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```
thinking that would take care of everything, but it doesn't.

Instead I get this error:

```
iisnode encountered an error when processing the request.

HRESULT: 0x6d
HTTP status: 500
HTTP subStatus: 1013
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

(node:1624) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: No `pages` directory found in C:\Inetpub\vhosts\******.com\test*******.com\server. Did you mean to run `nuxt` in the parent (`../`) directory?
    at Builder.build (C:\Inetpub\vhosts\********.com\test.*******.com\node_modules\nuxt\dist\nuxt.js:3670:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

In my server/server.js file, i changed the nuxt.config.js to :

`const config = require('../nuxt.config.js');`

And I modified my Pleask node 

```
Document Root:  /test.*******.com    
Application Mode: production  
Application URL: http://test.*******.com
Application Root: /test.*******.com   open  
Application Startup File:  server/server.js   edit  
```

I thin k the key here is this question in error: Did you mean to run `nuxt` in the parent (`../`) directory?

But I can't find a way to correct.

Any ideas?

Thank You in Advance

**Comment by lessenmytaxes** [comment]
**UPDATE:**

For the sake of expediency, I created an index.js in root with:

require('./server/server.js');

Changed web.config to point to index in root, and the same with Plesk node App startup file.

Everything workks fine and I can still have good housekeeping between server and client files
